"""empty message

Revision ID: 53f02f8f58e8
Revises: df4fa598c953
Create Date: 2021-06-10 18:13:05.023369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f02f8f58e8'
down_revision = 'df4fa598c953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('songId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'translations', 'songs', ['songId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_column('translations', 'songId')
    # ### end Alembic commands ###
